- id: '1533840808766'
  alias: Test
  trigger:
  - entity_id: device_tracker.redminote5redmi
    platform: state
    to: home
  condition: []
  action:
    service: light.turn_on
    entity_id: light.schlafzimmer